### ISSUE TITLE
several 1.7.0 downloads does not work and give: The requested path was not found.

### ISSUE THREAD

**Issue by tkleiber** [powermock/powermock#814]
On the download page https://github.com/powermock/powermock/wiki/Downloads following download links does not work:

https://dl.bintray.com/powermock/generic/distributions/powermock-mockito2-junit-1.7.0.zip
https://dl.bintray.com/powermock/generic/distributions/powermock-mockito2-testng-1.7.0.zip
https://dl.bintray.com/powermock/generic/distributions/powermock-easymock-1.7.0-full.jar
https://dl.bintray.com/powermock/generic/distributions/powermock-mockito-1.7.0-full.jar
https://dl.bintray.com/powermock/generic/distributions/powermock-mockito2-1.7.0-full.jar

**Comment by thekingnothing** [comment]
I fixed links for full jars. Mockito2 zip files wasn't uploaded for unknown reason. I'll upload them manually.

**Comment by daviessd** [comment]
Hi. Do we know when https://dl.bintray.com/powermock/generic/distributions/powermock-mockito2-1.7.0-full.jar will be loaded. The link is still broken.

Stuart

**Comment by thekingnothing** [comment]
Hi,

The jar was uploaded before, but wiki had broken links. Please, check links on wiki again.

Best regrads,
Arthur Zagretdinov

On 27 Jun 2017, at 11:56, daviessd <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi. Do we know when https://dl.bintray.com/powermock/generic/distributions/powermock-mockito2-1.7.0-full.jar will be loaded. The link is still broken.

Stuart

**Comment by daviessd** [comment]
Thanks for the reply.
Links are still broken. 
It was  https://dl.bintray.com/powermock/generic/distributions/powermock-mockito2-testng-1.7.0.zip I needed (I did update the post) 
I need a definitive list of the Jars for PowerMock 1.7.0 with Mockito2 and TestNG including dependencies. I have been adding random jars to my project to resolve the dependencies. Currently I am on org/powermock/api/mockito/expectation/WithOrWithoutExpectedArguments but as I am in the dark I cannot find it!

Stuart

**Comment by thekingnothing** [comment]
There were two issues:
- links to full-jars were broken on wiki. I have fixed the issue
- zip files for Mockito 2 is not uploaded to bintray. I'll upload them as soon I have opportunity. I hope, I'll do it later today or tomorrow morning.

As workaround you may use jars from maven card configuration:

```

<properties>
    <powermock.version>1.7.0</powermock.version>
</properties>
<dependencies>
   <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-module-testng</artifactId>
      <version>${powermock.version}</version>
      <scope>test</scope>
   </dependency>
   <dependency>
      <groupId>org.powermock</groupId>
      <artifactId>powermock-api-mockito2</artifactId>
      <version>${powermock.version}</version>
      <scope>test</scope>
   </dependency>
</dependencies>

```

Best regrads,
Arthur Zagretdinov

On 27 Jun 2017, at 14:11, daviessd <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the reply.
Links are still broken.
It was https://dl.bintray.com/powermock/generic/distributions/powermock-mockito2-testng-1.7.0.zip I needed (I did update the post)
I need a definitive list of the Jars for PowerMock 1.7.0 with Mockito2 and TestNG including dependencies. I have been adding random jars to my project to resolve the dependencies. Currently I am on org/powermock/api/mockito/expectation/WithOrWithoutExpectedArguments but as I am in the dark I cannot find it!

Stuart

**Comment by thekingnothing** [comment]
I've just uploaded reminding artifacts.
