### ISSUE TITLE
java.util.ServiceConfigurationError: not a subtype when using log4j2 2.9.x

### ISSUE THREAD

**Issue by d53dave** [powermock/powermock#861]
Hi,

we have been seeing some weird issues on our build server recently and after investigating found out that the problem stemmed from using powermock with log4j2 after upgrading log4j2 from 2.8.3 to 2.9.1. It seems to be a classloading issue and I am not sure the problem lies with powermock - but it might be.

Questionaire:
### What steps will reproduce the problem?
Have the class under test (or an injected class) get a log4j2 logger, i.e.
```java
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

[...]

final Logger logger = LogManager.getLogger(Example.class);
```

### What is the expected output?
Testing works with log4j2 2.9.x as it did with 2.8.x.

### What do you see instead?

```java
java.util.ServiceConfigurationError: org.apache.logging.log4j.spi.Provider: Provider org.apache.logging.log4j.core.impl.Log4jProvider not a subtype
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:376)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.apache.logging.log4j.util.ProviderUtil.loadProviders(ProviderUtil.java:101)
	at org.apache.logging.log4j.util.ProviderUtil.<init>(ProviderUtil.java:67)
	at org.apache.logging.log4j.util.ProviderUtil.lazyInit(ProviderUtil.java:142)
	at org.apache.logging.log4j.util.ProviderUtil.hasProviders(ProviderUtil.java:126)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:89)
	at com.company.project.module.logic.users.InjectedClassWithLogger.<clinit>(InjectedClassWithLogger.java:87)
	at sun.reflect.GeneratedSerializationConstructorAccessor6.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:14)
	at org.powermock.api.mockito.repackaged.ClassImposterizer.createProxy(ClassImposterizer.java:149)
	at org.powermock.api.mockito.repackaged.ClassImposterizer.imposterise(ClassImposterizer.java:64)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMethodInvocationControl(DefaultMockCreator.java:121)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.createMock(DefaultMockCreator.java:69)
	at org.powermock.api.mockito.internal.mockcreation.DefaultMockCreator.mock(DefaultMockCreator.java:46)
	at org.powermock.api.mockito.PowerMockito.mock(PowerMockito.java:201)
	at org.powermock.api.extension.listener.AnnotationEnabler.standardInject(AnnotationEnabler.java:118)
	at org.powermock.api.extension.listener.AnnotationEnabler.beforeTestMethod(AnnotationEnabler.java:63)
	at org.powermock.tests.utils.impl.PowerMockTestNotifierImpl.notifyBeforeTestMethod(PowerMockTestNotifierImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.executeTest(PowerMockJUnit44RunnerDelegateImpl.java:308)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTestInSuper(PowerMockJUnit47RunnerDelegateImpl.java:131)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.access$100(PowerMockJUnit47RunnerDelegateImpl.java:59)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner$TestExecutorStatement.evaluate(PowerMockJUnit47RunnerDelegateImpl.java:147)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.evaluateStatement(PowerMockJUnit47RunnerDelegateImpl.java:107)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl$PowerMockJUnit47MethodRunner.executeTest(PowerMockJUnit47RunnerDelegateImpl.java:82)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$PowerMockJUnit44MethodRunner.runBeforesThenTestThenAfters(PowerMockJUnit44RunnerDelegateImpl.java:298)
	at org.junit.internal.runners.MethodRoadie.runTest(MethodRoadie.java:86)
	at org.junit.internal.runners.MethodRoadie.run(MethodRoadie.java:49)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.invokeTestMethod(PowerMockJUnit44RunnerDelegateImpl.java:218)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.runMethods(PowerMockJUnit44RunnerDelegateImpl.java:160)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl$1.run(PowerMockJUnit44RunnerDelegateImpl.java:134)
	at org.junit.internal.runners.ClassRoadie.runUnprotected(ClassRoadie.java:33)
	at org.junit.internal.runners.ClassRoadie.runProtected(ClassRoadie.java:45)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.run(PowerMockJUnit44RunnerDelegateImpl.java:136)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.run(JUnit4TestSuiteChunkerImpl.java:121)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.run(AbstractCommonPowerMockRunner.java:57)
	at org.powermock.modules.junit4.PowerMockRunner.run(PowerMockRunner.java:59)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)


```

### What version of the product are you using? 
powermock-api-mockito 1.7.3
powermock-module-junit4 1.7.3
with
mockito-all 1.10.9

**Comment by ttelang** [comment]
log4j2 2.10 would have the following related changes - https://issues.apache.org/jira/browse/LOG4J2-2055

**Comment by thekingn0thing** [comment]
@d53dave  as I understand from the last comment the issue in not on PowerMock side. Could you try to upgrade the version of log4j2?  If the issue still can be reproduced then, please, reopen this issue.

**Comment by shirleyliu6666** [comment]
so what's the solution finally? I encountered the same issues.

**Comment by imdreamrunner** [comment]
same question here. what's the issue? i only encounter this issue when i use powermock.

**Comment by thekingn0thing** [comment]
The issue was with log4j 2.9.1 and fixed in 2.10.0 version. Solution - upgrade log4j to 2.10.0.

**Comment by cvcGitHub** [comment]
@imdreamrunner  Yes I do have the same problem when powermockito comes in picture...
Upgraded to log4j version 2.10.0 but still facing the same issue, any further suggestions e.g. the compatible version of powermockito for log4j 2.10.0 ???

**Comment by cvcGitHub** [comment]
@thekingnothing no luck with log4j 2.10.0  :(  
Powermock version I'm using is 1.6.5

**Comment by russelmorgan** [comment]
@thekingnothing I am still seeing it as well in 2.10.0 



```[ERROR] Caused by: java.lang.RuntimeException: Cannot create a new instance of test class class com.disney.guestcontroller.app.controller.versioned.RequestInitUtilityTest
[ERROR] 	at org.powermock.modules.testng.internal.TestClassInstanceFactory.create(TestClassInstanceFactory.java:59)
[ERROR] 	at org.powermock.modules.testng.internal.PowerMockClassloaderObjectFactory.newInstance(PowerMockClassloaderObjectFactory.java:46)
[ERROR] 	at org.powermock.modules.testng.PowerMockObjectFactory.newInstance(PowerMockObjectFactory.java:43)
[ERROR] 	at org.testng.internal.ClassHelper.createInstance1(ClassHelper.java:410)
[ERROR] 	... 26 more
[ERROR] Caused by: java.lang.reflect.InvocationTargetException
[ERROR] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ERROR] 	at org.powermock.modules.testng.internal.TestClassInstanceFactory.create(TestClassInstanceFactory.java:51)
[ERROR] 	... 29 more
[ERROR] Caused by: java.util.ServiceConfigurationError: org.apache.logging.log4j.util.PropertySource: Provider org.apache.logging.log4j.util.EnvironmentPropertySource not a subtype```

**Comment by codegrizzly** [comment]
I know it's a bit late, but I was able to fix this type of error by placing the following at the top of any test classes that use PowerMock.

`@PowerMockIgnore({"org.apache.logging.log4j.*"})`

**Comment by Bill** [comment]
Unfortunately, @codegrizzly, that `@PoerMockIgnore()` workaround won't work for me because I want to mock:

```java
PowerMockito.mockStatic(LogManager.class);
```

Interestingly, I see the `…not a subtype…` exception even with this:

```java
//@PrepareForTest(LogManager.class)

public class MyTest {

  @Rule
  public PowerMockRule powerMockRule = new PowerMockRule();
...
```

gives:

```sh
java.util.ServiceConfigurationError: org.slf4j.spi.SLF4JServiceProvider: Provider org.apache.logging.slf4j.SLF4JServiceProvider not a subtype
```

So even if I'm not trying to mock anything in log4j, its mere presence, with Powermock, seems to result in the exception.

**Comment by codegrizzly** [comment]
Sorry to hear that. I do know PowerMock has class loading issues with Log4j2. I try to avoid using PowerMock, especially mockStatic. I've gotten in the habit of wrapping static calls in classes under test with a local method. That way, I can just use mockito to mock the return of the wrapping method.

**Comment by philippebn** [comment]
> `Could not initialize class org.apache.logging.log4j.util.PropertiesUtil
java.lang.NoClassDefFoundError: Could not initialize class org.apache.logging.log4j.util.PropertiesUtil
	at org.apache.logging.log4j.status.StatusLogger.<clinit>(StatusLogger.java:71)
	at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:60)`



Got the same issue here with powermock '1.7.3' and log4j '2.10.0' and 2.10.1-SNAPSHOT

**Comment by gochev** [comment]
this is happening even with log4j 1.2.17

some projects cannot be updated to log4j2 :)

**Comment by vishaldeshmukh007** [comment]
My issue was resolved after adding **test scope dependency** of latest log4J i.e. 2.13.3.
PowerMock version is 2.0.2
